ALTER USER postgres WITH ENCRYPTED PASSWORD '{POSTGRES_PASSWORD}';
CREATE USER {USER_LOGIN};
ALTER ROLE {USER_LOGIN} WITH CREATEDB;
ALTER ROLE {USER_LOGIN} SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE DATABASE {USER_LOGIN} OWNER {USER_LOGIN};
ALTER USER {USER_LOGIN} WITH ENCRYPTED PASSWORD '{USER_PASSWORD}';
